myPollsApp/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myPollsApp.views.home', name='home'),
    # url(r'^myPollsApp/', include('myPollsApp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

)

polls/urls.py
# urlConf file for polls

from django.conf.urls import patterns, url


urlpatterns = patterns('',
    # should look like url('r^/$', views.index), 
    )

polls/models.py
from django.db import models

# Create your models here.

class Poll(models.Model):
    # complete your model here
    pass


class Choice(models.Model):
    # complete your model here
    pass

polls/views.py
# Create your views here.

# Don't forget to import modules!




def index(request):
    # complete the index function here

def detail(request, poll_id):
    # complete the detail function here

def results(request, poll_id):
    # complete the results function here
    pass

def vote(request, poll_id):
    # complete the vote function here
    pass

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>
<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="/polls/{{ poll.id }}/">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>